import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
page.on('console', msg => console.log('CONSOLE', msg.type(), msg.text()));
page.on('pageerror', err => console.log('PAGEERROR', err.message));
const resp = await page.goto('http://localhost:5173', { waitUntil: 'networkidle', timeout: 20000 });
console.log('STATUS', resp?.status());
await page.screenshot({ path: 'tmp-dev-5173.png', fullPage: true });
const txt = await page.textContent('body');
console.log('BODY_TEXT_LEN', (txt || '').trim().length);
await browser.close();
