// <auto-generated />
using System;
using IkOtomasyon.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IkOtomasyon.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IkOtomasyon.Api.Entities.AiEvaluationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompetencyAssessmentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceQuotesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputSnapshotHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OverallRecommendation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillAssessmentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationQuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId", "CandidateId", "InputSnapshotHash");

                    b.HasIndex("JobId", "CandidateId", "Version")
                        .IsUnique();

                    b.ToTable("AiEvaluationReports");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastUpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("StageId");

                    b.HasIndex("JobId", "CandidateId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.CandidateConsent", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<string>("ConsentTextVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DataRetentionDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeleteRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CandidateId");

                    b.ToTable("CandidateConsents");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("EducationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSnapshot")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExperienceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("TotalExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CandidateId");

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.CvDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("ParseError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("CvDocuments");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewCriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CriterionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EnrichedByModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EnrichmentErrorsJson")
                        .HasColumnType("text");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NONE");

                    b.Property<string>("EvaluatorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EvidenceQuotesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplacesScoreId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("SCORED");

                    b.HasKey("Id");

                    b.HasIndex("ReplacesScoreId");

                    b.HasIndex("ScorecardId", "CriterionKey", "CreatedAt");

                    b.ToTable("InterviewCriterionScores");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompetencyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepthJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceSnippetsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskFlagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TurnIndex");

                    b.ToTable("InterviewInsights");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuestionBankId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("InterviewMessages");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromTurnIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PlanRationaleJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlannedQuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "FromTurnIndex");

                    b.ToTable("InterviewPlans");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewQuestionBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "TopicKey", "IsActive");

                    b.ToTable("InterviewQuestionBanks");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewScorecard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RubricTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RubricTemplateId");

                    b.HasIndex("SessionId", "RubricTemplateId")
                        .IsUnique();

                    b.ToTable("InterviewScorecards");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AiLastPlanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AiMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("OFF");

                    b.Property<string>("AiModelName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompetencyWeightsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("MinExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<string>("NiceToHaveSkillsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredSkillsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.JobSkillWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkillNameNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "SkillNameNormalized")
                        .IsUnique();

                    b.ToTable("JobSkillWeights");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ComputedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GapsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId", "CandidateId")
                        .IsUnique();

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("PipelineStages");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RubricCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Key")
                        .IsUnique();

                    b.HasIndex("TemplateId", "Order");

                    b.ToTable("RubricCriteria");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RubricTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "IsDefault");

                    b.ToTable("RubricTemplates");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.AiEvaluationReport", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Application", "Application")
                        .WithMany("AiEvaluationReports")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("IkOtomasyon.Api.Entities.Candidate", "Candidate")
                        .WithMany("AiEvaluationReports")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.JobPosting", "Job")
                        .WithMany("AiEvaluationReports")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Application", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Candidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.JobPosting", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.PipelineStage", "Stage")
                        .WithMany("Applications")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.CandidateConsent", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Candidate", "Candidate")
                        .WithOne("Consent")
                        .HasForeignKey("IkOtomasyon.Api.Entities.CandidateConsent", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.CandidateProfile", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Candidate", "Candidate")
                        .WithOne("Profile")
                        .HasForeignKey("IkOtomasyon.Api.Entities.CandidateProfile", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.CvDocument", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Candidate", "Candidate")
                        .WithMany("CvDocuments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewCriterionScore", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.InterviewCriterionScore", "ReplacesScore")
                        .WithMany()
                        .HasForeignKey("ReplacesScoreId");

                    b.HasOne("IkOtomasyon.Api.Entities.InterviewScorecard", "Scorecard")
                        .WithMany("CriterionScores")
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplacesScore");

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewInsight", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.InterviewSession", "Session")
                        .WithMany("Insights")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewMessage", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.InterviewQuestionBank", "QuestionBank")
                        .WithMany()
                        .HasForeignKey("QuestionBankId");

                    b.HasOne("IkOtomasyon.Api.Entities.InterviewSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionBank");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewPlan", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.InterviewSession", "Session")
                        .WithMany("Plans")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewScorecard", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.RubricTemplate", "RubricTemplate")
                        .WithMany("Scorecards")
                        .HasForeignKey("RubricTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.InterviewSession", "Session")
                        .WithMany("Scorecards")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubricTemplate");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewSession", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Application", "Application")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.JobSkillWeight", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.JobPosting", "Job")
                        .WithMany("SkillWeights")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.MatchResult", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.JobPosting", "Job")
                        .WithMany("MatchResults")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RolePermission", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RubricCriterion", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.RubricTemplate", "Template")
                        .WithMany("Criteria")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RubricTemplate", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.JobPosting", "Job")
                        .WithMany("RubricTemplates")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.UserRole", b =>
                {
                    b.HasOne("IkOtomasyon.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IkOtomasyon.Api.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Application", b =>
                {
                    b.Navigation("AiEvaluationReports");

                    b.Navigation("InterviewSessions");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Candidate", b =>
                {
                    b.Navigation("AiEvaluationReports");

                    b.Navigation("Applications");

                    b.Navigation("Consent");

                    b.Navigation("CvDocuments");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewScorecard", b =>
                {
                    b.Navigation("CriterionScores");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.InterviewSession", b =>
                {
                    b.Navigation("Insights");

                    b.Navigation("Messages");

                    b.Navigation("Plans");

                    b.Navigation("Scorecards");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.JobPosting", b =>
                {
                    b.Navigation("AiEvaluationReports");

                    b.Navigation("Applications");

                    b.Navigation("MatchResults");

                    b.Navigation("RubricTemplates");

                    b.Navigation("SkillWeights");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.PipelineStage", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.RubricTemplate", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Scorecards");
                });

            modelBuilder.Entity("IkOtomasyon.Api.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
